name: Bug report
description: Report a bug, otherwise see the links below
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the code of conduct before proceeding.
      options:
        - label: I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I've found a bug and checked that ...
      description: Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
      options:
      - label: I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
        required: true
      - label: I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
        required: true
      - label: I have understood that answers are voluntary and community-driven, and not commercial support.
        required: true
      - label: I have verified that my issue has not been already answered in the past. I've read the [Common issues documentation section](https://docs.cryptpad.org/en/FAQ.html#common-issues) and I also checked [previous issues](https://github.com/xwiki-labs/cryptpad/issues).
        required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a brief description of the bug in 1-2 sentences. If applicable, add screenshots to help explain your problem. Very useful for bugs in CryptPad UI.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe the steps to reproduce the bug. Screenshots can be added, if helpful.
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What opreating system are you using?
      multiple: true
      options:
        - Linux/BSD/UNIX
        - Microsoft Windows
        - Apple macOS
        - Apple iOS
        - Google ChromeOS
        - Google Android
        - Other
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Mozilla Firefox
        - Google Chrome
        - Apple Safari
        - Microsoft Edge
        - Other
  - type: textarea
    id: extensions
    attributes:
      label: Extensions
      description: Web browser extensions installed
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of CryptPad are you running?
      options:
        - 5.3.0
        - 5.2.1
        - 5.2.0
        - 5.1.0
        - 5.0.0
        - 4.14.1
        - 4.14.0
        - 4.13.0
        - 4.12.1
        - 4.12.0
        - 4.11.0
        - 4.10.0
        - Other
    validations:
      required: true
